import { FormEvent, useEffect, useMemo, useState } from 'react'
import { CalendarClock, MapPin, Phone, Plus, Search, Users } from 'lucide-react'
import { CUSTOMER_STAGES, createCustomer, customerOutstanding, customerProgress, fetchCustomers, type Customer, type CustomerStage } from '../lib/customers'

type Mode = 'journey-dashboard' | 'customers' | 'followups' | 'pipeline'
type Props = { tenantId: string; mode: Mode }

const blank = { name:'', mobile:'', email:'', village:'', address:'', systemSize:'', stage:'Inquiry' as CustomerStage, nextFollowup:'', nextAction:'', dealAmount:'', notes:'' }
const money = (v:number) => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0)

export default function CustomerJourneyModule({tenantId,mode}:Props){
  const [rows,setRows]=useState<Customer[]>([]),[term,setTerm]=useState(''),[stage,setStage]=useState<'all'|CustomerStage>('all')
  const [showAdd,setShowAdd]=useState(false),[selected,setSelected]=useState<Customer|null>(null),[form,setForm]=useState(blank),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
  const load=async()=>{setLoading(true);try{setRows(await fetchCustomers(tenantId))}catch(e){setMessage(e instanceof Error?e.message:'Unable to load customers.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[tenantId])
  const filtered=useMemo(()=>rows.filter(c=>{const q=term.toLowerCase().trim();const ok=!q||[c.name,c.customerId,c.mobile,c.village||'',String(c.systemSize||'')].some(v=>v.toLowerCase().includes(q));if(stage!=='all'&&c.stage!==stage)return false;if(mode==='followups'&&!c.nextFollowup)return false;if(mode==='pipeline'&&c.stage==='Completed')return false;return ok}),[rows,term,stage,mode])
  const add=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{await createCustomer(tenantId,{name:form.name.trim(),mobile:form.mobile.trim(),email:form.email||null,village:form.village||null,address:form.address||null,systemSize:form.systemSize?Number(form.systemSize):null,stage:form.stage,leadStatus:'New',assignedTo:null,nextFollowup:form.nextFollowup||null,nextAction:form.nextAction||null,dealAmount:form.dealAmount?Number(form.dealAmount):0,notes:form.notes||null});setForm(blank);setShowAdd(false);await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to add customer.')}finally{setSaving(false)}}
  const title=mode==='customers'?'Customers':mode==='followups'?'Follow-ups':mode==='pipeline'?'Pipeline':'Customer Journey'
  return <div className="module-stack">
    <div className="module-head"><div><h1>{title}</h1><p>{mode==='journey-dashboard'?'Track every solar customer from inquiry to completed installation.':loading?'Loading…':`${filtered.length} customer(s)`}</p></div><button className="primary tenant-primary" onClick={()=>setShowAdd(true)}><Plus size={16}/> Add Customer</button></div>
    {mode==='journey-dashboard'&&<div className="journey-stage-grid">{CUSTOMER_STAGES.map(s=><article key={s}><span>{s}</span><strong>{rows.filter(r=>r.stage===s).length}</strong><small>Journey stage</small></article>)}</div>}
    {mode!=='journey-dashboard'&&<div className="customer-filters"><div className="search-box"><Search size={17}/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search name, ID, phone, village or kW"/></div><select value={stage} onChange={e=>setStage(e.target.value as 'all'|CustomerStage)}><option value="all">All stages</option>{CUSTOMER_STAGES.map(s=><option key={s}>{s}</option>)}</select></div>}
    {message&&<div className="notice">{message}</div>}
    <div className="customer-list">{(mode==='journey-dashboard'?rows.slice(0,8):filtered).map(c=><button key={c.id} className="customer-card" onClick={()=>setSelected(c)}><div className="customer-card-top"><div><strong>{c.name}</strong><small>{c.customerId}{c.systemSize?` · ${c.systemSize} kW`:''}</small></div><span className="stage-pill">{c.stage}</span></div><div className="customer-meta"><span><Phone size={14}/>{c.mobile}</span>{c.village&&<span><MapPin size={14}/>{c.village}</span>}<span><CalendarClock size={14}/>{c.nextFollowup||'No follow-up'}</span></div><div className="customer-financial"><span><small>Deal</small><strong>{money(c.dealAmount)}</strong></span><span><small>Outstanding</small><strong>{money(customerOutstanding(c))}</strong></span><span><small>Next</small><strong>{c.nextAction||'—'}</strong></span></div><div className="progress"><span style={{width:`${customerProgress(c)}%`}}/></div></button>)}{!loading&&rows.length===0&&<section className="panel empty-state"><Users size={28}/><h3>No customers yet</h3><p className="muted">Add the first inquiry/customer.</p></section>}</div>
    {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="modal customer-profile" onMouseDown={e=>e.stopPropagation()}><div className="panel-title"><div><p className="eyebrow">CUSTOMER PROFILE</p><h2>{selected.name}</h2></div><button className="ghost" onClick={()=>setSelected(null)}>Close</button></div><div className="profile-grid"><article><span>Customer ID</span><strong>{selected.customerId}</strong></article><article><span>Mobile</span><strong>{selected.mobile}</strong></article><article><span>Stage</span><strong>{selected.stage}</strong></article><article><span>System Size</span><strong>{selected.systemSize?`${selected.systemSize} kW`:'—'}</strong></article><article><span>Deal</span><strong>{money(selected.dealAmount)}</strong></article><article><span>Outstanding</span><strong>{money(customerOutstanding(selected))}</strong></article></div><section className="panel inner-panel"><h3>Follow-up / Pipeline</h3><p>{selected.nextFollowup||'No date'} · {selected.nextAction||'No next action'}</p></section><section className="panel inner-panel"><h3>Address & Notes</h3><p>{selected.address||selected.village||'No address added.'}</p><p className="muted">{selected.notes||'No notes yet.'}</p></section></section></div>}
    {showAdd&&<div className="modal-backdrop" onMouseDown={()=>setShowAdd(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="panel-title"><div><p className="eyebrow">CUSTOMER JOURNEY</p><h2>Add Inquiry/Customer</h2></div><button className="ghost" onClick={()=>setShowAdd(false)}>Close</button></div><form className="form-grid" onSubmit={add}><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Mobile<input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Village<input value={form.village} onChange={e=>setForm({...form,village:e.target.value})}/></label><label>System size (kW)<input type="number" step="0.1" value={form.systemSize} onChange={e=>setForm({...form,systemSize:e.target.value})}/></label><label>Stage<select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value as CustomerStage})}>{CUSTOMER_STAGES.map(s=><option key={s}>{s}</option>)}</select></label><label>Next follow-up<input type="date" value={form.nextFollowup} onChange={e=>setForm({...form,nextFollowup:e.target.value})}/></label><label>Next action<input value={form.nextAction} onChange={e=>setForm({...form,nextAction:e.target.value})}/></label><label>Deal amount<input type="number" value={form.dealAmount} onChange={e=>setForm({...form,dealAmount:e.target.value})}/></label><label className="full-field">Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="full-field">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="form-actions"><button type="button" className="ghost" onClick={()=>setShowAdd(false)}>Cancel</button><button className="primary tenant-primary" disabled={saving}>{saving?'Saving…':'Save Customer'}</button></div></form></section></div>}
  </div>
}
